apiVersion: v1
kind: Service
metadata:
  name: pgadmin-nodeport
spec:
  type: NodePort
  selector:
    app: data-lab-cluster-pgadmin4
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
