apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer
  namespace: data-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer
  template:
    metadata:
      labels:
        app: cdc-consumer
    spec:
      containers:
        - name: consumer
          image: cdc-consumer:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              value: "redpanda-0.redpanda.data-lab.svc.cluster.local:9093"
